site_name: Cookbook
theme:
  name: material
  icon:
    logo: material/book

  palette:
    - scheme: default
      primary: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.sections
    - navigation.tracking
    - navigation.indexes

plugins: 
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  generator: false

extra_css:
  - "stylesheets/extra.css"