site_name: Cookbook
theme:
  name: material

  icon:
    repo: fontawesome/brands/fork-knife

  palette:
    - scheme: default
      primary: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences